global:
  issuer: https://quarterdeck.svc.cluster.local
  origins:
    - https://quarterdeck.svc.cluster.local
    - https://endeavor.svc.cluster.local

quarterdeck:

  docsName: "Testing Documentation"
  supportEmail: "testing@support.io"

  database:
    URL:
      secretKeyRef:
        name: quarterdeck-database-credentials
        key: database-url
    readOnly: true

  securitytxt:
    text: |
      Contact: mailto:security@example.com
      Expires: 2037-11-14T22:07:00.000Z
      Encryption: https://example.com/pgp-key.txt
      Preferred-Languages: en
      Canonical: https://example.com/.well-known/security.txt
      Policy: https://example.com/security

  auth:
    keys:
      01K3KXRFKSVV9HQ26GD6RRBEK9: /data/jwks/01K3KXRFKSVV9HQ26GD6RRBEK9.pem

  app:
    name: Endeavor
    logoURI: https://endeavor.co/static/img/logo.png
    baseURI: https://endeavor.co

    # welcomeEmail:
    #   create: false
    #   configMap: "endeavor-welcome-email-templates"

    welcomeEmail:
      create: true
      textTemplate:
        value: |-
          - What is {{ .AppName }}?

          {{ .AppName }} is a shared workspace where teams collaborate to prototype, evaluate, and deploy AI agents into real business workflows with full visibility and control.

          - Why You’re Invited

          Your expertise is needed. {{ .OrgName }} is using {{ .AppName }} to work across technical and business teams to implement AI responsibly and transparently, and joining gives you access to the workflows, evaluations, and decisions that make that possible.

          - Your role: {{ if .Role }}{{ .Role }}{{ else }}Team Member{{ end }}

      htmlTemplate:
        value: |-
          <h3 style="padding: 12px 0; margin: 0;">What is {{ .AppName }}?</h3>
          <p style="padding: 12px 0; margin: 0;">{{ .AppName }} is a shared workspace where teams collaborate to prototype, evaluate, and deploy AI agents into real business workflows with full visibility and control.</p>

          <h3 style="padding: 12px 0; margin: 0;">Why You’re Invited</h3>
          <p style="padding: 12px 0; margin: 0;">Your expertise is needed. {{ .OrgName }} is using {{ .AppName }} to work across technical and business teams to implement AI responsibly and transparently, and joining gives you access to the workflows, evaluations, and decisions that make that possible.</p>

          <h3 style="padding: 12px 0; margin: 0;">Your role: {{ if .Role }}{{ .Role }}{{ else }}Team Member{{ end }}</h3>

  org:
    name: Acme, Inc.
    streetAddress: 12 Center Lane; Barnaby CT 44120
    homepage: https://acme.com
    supportEmail: support@acme.com

  email:
    sender:
      email: "server@testing.io"
      name: "Admin Team"

    method: "sendgrid"

    sendgrid:
      apiKey:
        secretKeyRef:
          name: quarterdeck-sendgrid-credentials
          key: sendgrid-api-key

secrets:
  jwks:
    secretName: rotational-jwks


opentelemetry:
  serviceName: guidelight
  resourceAttributes:
    service.namespace: rotational
    service.version: 0.1.0
    service.environment: development

  exporter:
    otlp:
      endpoint: opentelemetry-collector.opentelemetry.svc.cluster.local:4317
      headers:
        "x-api-key": "1234567890"
        "Authorization": "Bearer $JWT_TOKEN"
      timeout: 10000
      protocol: grpc
