global:
  issuer: https://quarterdeck.svc.cluster.local
  origins:
    - https://quarterdeck.svc.cluster.local
    - https://endeavor.svc.cluster.local

quarterdeck:

  docsName: "Testing Documentation"
  supportEmail: "testing@support.io"

  database:
    URL:
      secretKeyRef:
        name: quarterdeck-database-credentials
        key: database-url
    readOnly: true

  securitytxt:
    text: |
      Contact: mailto:security@example.com
      Expires: 2037-11-14T22:07:00.000Z
      Encryption: https://example.com/pgp-key.txt
      Preferred-Languages: en
      Canonical: https://example.com/.well-known/security.txt
      Policy: https://example.com/security

  auth:
    keys:
      01K3KXRFKSVV9HQ26GD6RRBEK9: /data/jwks/01K3KXRFKSVV9HQ26GD6RRBEK9.pem

  email:
    sender:
      email: "server@testing.io"
      name: "Admin Team"

    method: "sendgrid"

    sendgrid:
      apiKey:
        secretKeyRef:
          name: quarterdeck-sendgrid-credentials
          key: sendgrid-api-key

  usersync:
    webhooks:
      - "https://example.com/webhook1"
      - "https://example.com/webhook2"

secrets:
  jwks:
    secretName: rotational-jwks
