apiVersion: v2
name: opentelemetry
description: Configure OpenTelemetry environment variables for your application.

# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: library

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# Project Information
home: https://rotational.io
icon: https://rotational.io/img/favicon.png
sources:
  - https://github.com/rotationalio/helm-charts
maintainers:
  - name: rotationalio
    email: support@rotational.io