apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.{{ .Values.groupName }}
  labels:
    {{- include "acme-linode.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ include "acme-linode.namespace" . }}/{{ include "acme-linode.servingCertificate" . }}"
spec:
  group: {{ .Values.groupName }}
  groupPriorityMinimum: 1000
  versionPriority: 15
  version: v1alpha1
  service:
    name: {{ include "acme-linode.fullname" . }}
    namespace: {{ include "acme-linode.namespace" . | quote }}