apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acme-linode.fullname" . }}
  namespace: {{ include "acme-linode.namespace" . | quote }}
  labels:
    {{- include "acme-linode.labels" . | nindent 4 }}
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "acme-linode.fullname" . }}:webhook-authentication-reader
  namespace: kube-system
  labels:
    {{- include "acme-linode.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "acme-linode.fullname" . }}
    namespace: {{ include "acme-linode.namespace" . | quote }}
---
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "acme-linode.fullname" . }}:auth-delegator
  labels:
    {{- include "acme-linode.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "acme-linode.fullname" . }}
    namespace: {{ include "acme-linode.namespace" . | quote }}
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "acme-linode.fullname" . }}:domain-solver
  labels:
    {{- include "acme-linode.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - {{ .Values.groupName }}
    resources:
      - '*'
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "acme-linode.fullname" . }}:domain-solver
  labels:
    {{- include "acme-linode.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "acme-linode.fullname" . }}:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ .Values.certManager.serviceAccountName }}
    namespace: {{ .Values.certManager.namespace }}
---
# Grant the webhook permission to read the linode-credentials secret as specified either
# in the values or in the Certificates requesting the DNS01 challenge. Because any
# secret can be specified in any namespace, the webhook needs to be able to read all
# secrets in the cluster; which isn't ideal but is necessary given the current design.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "acme-linode.fullname" . }}:secret-reader
  labels:
    {{- include "acme-linode.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - 'get'
      - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "acme-linode.fullname" . }}:secret-reader
  labels:
    {{- include "acme-linode.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "acme-linode.fullname" . }}:secret-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "acme-linode.fullname" . }}
    namespace: {{ include "acme-linode.namespace" . | quote }}