{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ include "acme-linode.namespace" . | quote }}
  labels:
    {{- include "acme-linode.labels" . | nindent 4 }}
data:
  {{ .Values.secret.key }}: {{ .Values.secret.value | b64enc }}
{{- end }}